-- Setup and preflight only. No model inference in this file.
-- Requires sql/00_layer_contract.sql and a user-approved development database.
-- Run in one session with sql/31_score_approved_batch.sql; one writer only.
-- Existing TEXT_ITEM_SCORED data is left untouched. See docs/09_measured_exercise.md.

CREATE TABLE IF NOT EXISTS STUDIO_DS.RAW.TEXT_ITEM (
    ITEM_KEY VARCHAR,
    TITLE_ID NUMBER,
    AUTHOR_HASH VARCHAR,
    ITEM_TEXT VARCHAR,
    ITEM_DATE DATE,
    LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW STUDIO_DS.CURATED.TEXT_ITEM_DEDUPED AS
SELECT
    SHA2(TO_JSON(ARRAY_CONSTRUCT(TITLE_ID, AUTHOR_HASH, ITEM_TEXT)), 256) AS ITEM_HASH,
    TITLE_ID,
    AUTHOR_HASH,
    ITEM_TEXT,
    MIN(ITEM_DATE) AS ITEM_DATE
FROM STUDIO_DS.RAW.TEXT_ITEM
WHERE TITLE_ID IS NOT NULL
  AND ITEM_TEXT IS NOT NULL
  AND LENGTH(ITEM_TEXT) BETWEEN 8 AND 2000
GROUP BY 1, 2, 3, 4;

CREATE OR REPLACE VIEW STUDIO_DS.CURATED.TEXT_SCORING_CONFIG AS
WITH configuration AS (
    SELECT
        'enrichment-v2' AS PIPELINE_VERSION,
        'ai_sentiment:managed;ai_classify:managed' AS MODEL_POLICY,
        ['WILL_ATTEND', 'INTERESTED', 'WILL_NOT_ATTEND', 'OFF_TOPIC'] AS CATEGORIES,
        OBJECT_CONSTRUCT(
            'task_description',
            'Classify the author\'s explicit intent to attend this film in a theater. '
            || 'Enthusiasm alone is INTERESTED, not WILL_ATTEND. '
            || 'Use OFF_TOPIC when no attendance interest or intent is expressed.',
            'output_mode', 'single'
        ) AS CLASSIFY_CONFIG
)
SELECT *, SHA2(TO_JSON(ARRAY_CONSTRUCT(
    PIPELINE_VERSION, MODEL_POLICY, CATEGORIES,
    CLASSIFY_CONFIG:task_description::VARCHAR,
    CLASSIFY_CONFIG:output_mode::VARCHAR
)), 256) AS SCORER_VERSION
FROM configuration;

CREATE TABLE IF NOT EXISTS STUDIO_DS.CURATED.TEXT_ENRICHMENT_RESULT (
    ITEM_HASH VARCHAR NOT NULL,
    SCORER_VERSION VARCHAR NOT NULL,
    TITLE_ID NUMBER NOT NULL,
    ITEM_DATE DATE,
    PIPELINE_VERSION VARCHAR NOT NULL,
    MODEL_POLICY VARCHAR NOT NULL,
    SENTIMENT_RESPONSE VARIANT,
    INTENT_RESPONSE VARIANT,
    SENTIMENT VARCHAR,
    INTENT VARCHAR,
    SCORE_STATUS VARCHAR NOT NULL,
    RUN_ID VARCHAR NOT NULL,
    SCORING_QUERY_ID VARCHAR NOT NULL,
    SCORED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'GRAIN: one row per (ITEM_HASH, SCORER_VERSION). Single writer. Includes failed attempts for review; not an exactly-once inference guarantee.';

CREATE OR REPLACE VIEW STUDIO_DS.CURATED.TEXT_ITEMS_TO_SCORE AS
SELECT item.*, config.PIPELINE_VERSION, config.MODEL_POLICY,
       config.CATEGORIES, config.CLASSIFY_CONFIG, config.SCORER_VERSION
FROM STUDIO_DS.CURATED.TEXT_ITEM_DEDUPED item
CROSS JOIN STUDIO_DS.CURATED.TEXT_SCORING_CONFIG config
WHERE NOT EXISTS (
    SELECT 1 FROM STUDIO_DS.CURATED.TEXT_ENRICHMENT_RESULT result
    WHERE result.ITEM_HASH = item.ITEM_HASH
      AND result.SCORER_VERSION = config.SCORER_VERSION
);

SET SCORING_APPROVED = FALSE;
SET ENRICHMENT_RUN_ID = UUID_STRING();

CREATE OR REPLACE TEMPORARY TABLE STUDIO_DS.OPS.TEXT_SCORING_BATCH AS
SELECT * FROM STUDIO_DS.CURATED.TEXT_ITEMS_TO_SCORE
ORDER BY ITEM_HASH
LIMIT 100;

CREATE OR REPLACE TEMPORARY TABLE STUDIO_DS.OPS.TEXT_SCORING_ESTIMATE AS
WITH estimates AS (
    SELECT
        AI_COUNT_TOKENS('ai_sentiment', ITEM_TEXT) AS SENTIMENT_INPUT_TOKENS,
        AI_COUNT_TOKENS('ai_classify', ITEM_TEXT, CATEGORIES, CLASSIFY_CONFIG)
            AS CLASSIFY_INPUT_TOKENS
    FROM STUDIO_DS.OPS.TEXT_SCORING_BATCH
)
SELECT
    COUNT(*) AS BATCH_ROWS,
    COUNT(*) - COUNT(SENTIMENT_INPUT_TOKENS + CLASSIFY_INPUT_TOKENS) AS NULL_ESTIMATE_ROWS,
    SUM(SENTIMENT_INPUT_TOKENS) AS SENTIMENT_INPUT_TOKENS,
    SUM(CLASSIFY_INPUT_TOKENS) AS CLASSIFY_INPUT_TOKENS,
    SUM(SENTIMENT_INPUT_TOKENS + CLASSIFY_INPUT_TOKENS) AS TOTAL_INPUT_TOKENS,
    100000 AS INPUT_TOKEN_CEILING
FROM estimates;

SELECT *, CASE
    WHEN BATCH_ROWS = 0 THEN 'NO_WORK'
    WHEN NULL_ESTIMATE_ROWS > 0 THEN 'STOP: incomplete estimate'
    WHEN TOTAL_INPUT_TOKENS > INPUT_TOKEN_CEILING THEN 'STOP: reduce batch'
    ELSE 'AWAITING_APPROVAL: input estimate only, not a credit quote'
END AS PREFLIGHT_STATUS
FROM STUDIO_DS.OPS.TEXT_SCORING_ESTIMATE;

CREATE OR REPLACE VIEW STUDIO_DS.CURATED.TEXT_SENTIMENT_BY_TITLE AS
SELECT
    item.TITLE_ID,
    item.ITEM_DATE,
    COUNT(*) AS ELIGIBLE_ITEMS,
    COUNT(CASE WHEN result.SCORE_STATUS = 'SUCCEEDED' THEN 1 END) AS SCORED_ITEMS,
    COUNT(CASE WHEN result.SCORE_STATUS = 'REVIEW_REQUIRED' THEN 1 END) AS REVIEW_ITEMS,
    COUNT(CASE WHEN result.ITEM_HASH IS NULL THEN 1 END) AS UNSCORED_ITEMS,
    SCORED_ITEMS / NULLIF(COUNT(*), 0) AS SCORING_COVERAGE,
    COUNT(CASE WHEN result.SCORE_STATUS = 'SUCCEEDED' AND result.SENTIMENT = 'positive' THEN 1 END)
        / NULLIF(SCORED_ITEMS, 0) AS POSITIVE_SHARE_OF_SCORED,
    COUNT(CASE WHEN result.SCORE_STATUS = 'SUCCEEDED' AND result.INTENT = 'WILL_ATTEND' THEN 1 END)
        / NULLIF(SCORED_ITEMS, 0) AS ATTEND_INTENT_SHARE_OF_SCORED
FROM STUDIO_DS.CURATED.TEXT_ITEM_DEDUPED item
CROSS JOIN STUDIO_DS.CURATED.TEXT_SCORING_CONFIG config
LEFT JOIN STUDIO_DS.CURATED.TEXT_ENRICHMENT_RESULT result
    ON result.ITEM_HASH = item.ITEM_HASH AND result.SCORER_VERSION = config.SCORER_VERSION
GROUP BY item.TITLE_ID, item.ITEM_DATE;

CREATE TABLE IF NOT EXISTS STUDIO_DS.OPS.INTENT_GOLD (
    ITEM_HASH VARCHAR NOT NULL,
    ITEM_TEXT VARCHAR,
    TRUE_INTENT VARCHAR NOT NULL,
    LABELED_BY VARCHAR,
    LABELED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'GRAIN: one human-labeled row per ITEM_HASH. Include all supported classes.';