-- BILLABLE. Requires the same session and completed preflight from sql/30.
-- After reviewing the estimate, explicitly run SET SCORING_APPROVED = TRUE.
-- Serial runs only. A standard-table MERGE does not enforce concurrent uniqueness.
-- If persistence fails, retry only the MERGE below using the retained responses.

SET ENRICHMENT_QUERY_TAG = 'workload=text_enrichment;run=' || $ENRICHMENT_RUN_ID;
ALTER SESSION SET QUERY_TAG = $ENRICHMENT_QUERY_TAG;

CREATE OR REPLACE TEMPORARY TABLE STUDIO_DS.OPS.TEXT_SCORING_RESPONSES AS
SELECT batch.ITEM_HASH, batch.SCORER_VERSION, batch.TITLE_ID, batch.ITEM_DATE,
       batch.PIPELINE_VERSION, batch.MODEL_POLICY,
       AI_SENTIMENT(batch.ITEM_TEXT, TRUE) AS SENTIMENT_RESPONSE,
       AI_CLASSIFY(batch.ITEM_TEXT, batch.CATEGORIES, batch.CLASSIFY_CONFIG, TRUE)
           AS INTENT_RESPONSE
FROM STUDIO_DS.OPS.TEXT_SCORING_BATCH batch
CROSS JOIN STUDIO_DS.OPS.TEXT_SCORING_ESTIMATE estimate
WHERE $SCORING_APPROVED = TRUE
  AND estimate.NULL_ESTIMATE_ROWS = 0
  AND estimate.TOTAL_INPUT_TOKENS <= estimate.INPUT_TOKEN_CEILING
  AND NOT EXISTS (
      SELECT 1 FROM STUDIO_DS.CURATED.TEXT_ENRICHMENT_RESULT result
      WHERE result.ITEM_HASH = batch.ITEM_HASH AND result.SCORER_VERSION = batch.SCORER_VERSION
  );

SET SCORING_QUERY_ID = LAST_QUERY_ID();
SET SCORING_APPROVED = FALSE;

MERGE INTO STUDIO_DS.CURATED.TEXT_ENRICHMENT_RESULT target
USING (
    SELECT *,
        SENTIMENT_RESPONSE:value:categories[0]:sentiment::VARCHAR AS SENTIMENT,
        INTENT_RESPONSE:value:labels[0]::VARCHAR AS INTENT,
        CASE WHEN SENTIMENT IN ('positive', 'negative', 'neutral', 'mixed', 'unknown')
                  AND INTENT IN ('WILL_ATTEND', 'INTERESTED', 'WILL_NOT_ATTEND', 'OFF_TOPIC')
                  AND (SENTIMENT_RESPONSE:error IS NULL OR IS_NULL_VALUE(SENTIMENT_RESPONSE:error))
                  AND (INTENT_RESPONSE:error IS NULL OR IS_NULL_VALUE(INTENT_RESPONSE:error))
             THEN 'SUCCEEDED' ELSE 'REVIEW_REQUIRED' END AS SCORE_STATUS
    FROM STUDIO_DS.OPS.TEXT_SCORING_RESPONSES
) source
ON target.ITEM_HASH = source.ITEM_HASH AND target.SCORER_VERSION = source.SCORER_VERSION
WHEN NOT MATCHED THEN INSERT (
    ITEM_HASH, SCORER_VERSION, TITLE_ID, ITEM_DATE, PIPELINE_VERSION, MODEL_POLICY,
    SENTIMENT_RESPONSE, INTENT_RESPONSE, SENTIMENT, INTENT, SCORE_STATUS, RUN_ID, SCORING_QUERY_ID
) VALUES (
    source.ITEM_HASH, source.SCORER_VERSION, source.TITLE_ID, source.ITEM_DATE,
    source.PIPELINE_VERSION, source.MODEL_POLICY, source.SENTIMENT_RESPONSE,
    source.INTENT_RESPONSE, source.SENTIMENT, source.INTENT, source.SCORE_STATUS,
    $ENRICHMENT_RUN_ID, $SCORING_QUERY_ID
);

SELECT $ENRICHMENT_RUN_ID AS RUN_ID, $SCORING_QUERY_ID AS SCORING_QUERY_ID,
       COUNT(*) AS ATTEMPTED_ITEMS,
       COUNT(CASE WHEN result.SCORE_STATUS = 'REVIEW_REQUIRED' THEN 1 END) AS REVIEW_ITEMS
FROM STUDIO_DS.OPS.TEXT_SCORING_RESPONSES response
JOIN STUDIO_DS.CURATED.TEXT_ENRICHMENT_RESULT result
    ON result.ITEM_HASH = response.ITEM_HASH AND result.SCORER_VERSION = response.SCORER_VERSION;

ALTER SESSION UNSET QUERY_TAG;