-- Read-only, independent queries. Last 30 complete calendar days in session timezone.
-- Requires access to the relevant ACCOUNT_USAGE views, e.g. SNOWFLAKE.USAGE_VIEWER.
-- No rows means no observed records, not proof of no usage. Check access/latency first.
-- Product boundaries differ: these outputs are NOT an additive account invoice.
-- Sources and latency: docs/06_cost_model.md. Reviewed 2026-09-17.

-- 1. Current AI Functions credits by day, function and model, including in-flight usage.
SELECT DATE_TRUNC('day', START_TIME) AS USAGE_DAY, FUNCTION_NAME, MODEL_NAME,
       SUM(CREDITS) AS AI_FUNCTION_CREDITS,
       COUNT(DISTINCT QUERY_ID) AS QUERIES
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND START_TIME < CURRENT_DATE()
GROUP BY 1, 2, 3
ORDER BY USAGE_DAY DESC, AI_FUNCTION_CREDITS DESC;

-- 2. Tokens/pages by metric. Do not sum CREDITS after flattening METRICS.
SELECT usage.FUNCTION_NAME, usage.MODEL_NAME,
       metric.VALUE:key:metric::VARCHAR AS METRIC_TYPE,
       metric.VALUE:key:unit::VARCHAR AS UNIT,
       SUM(metric.VALUE:value::NUMBER) AS UNITS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY usage,
     LATERAL FLATTEN(INPUT => usage.METRICS) metric
WHERE usage.START_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND usage.START_TIME < CURRENT_DATE()
GROUP BY 1, 2, 3, 4
ORDER BY UNITS DESC;

-- 3. Expensive SQL inference queries. One usage row is not one scored item.
SELECT QUERY_ID, QUERY_TAG, USER_ID, WAREHOUSE_ID,
       MIN(START_TIME) AS FIRST_USAGE_WINDOW,
       SUM(CREDITS) AS AI_FUNCTION_CREDITS,
       BOOLOR_AGG(IS_COMPLETED) AS COMPLETED_IN_WINDOW
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND START_TIME < CURRENT_DATE()
GROUP BY QUERY_ID, QUERY_TAG, USER_ID, WAREHOUSE_ID
ORDER BY AI_FUNCTION_CREDITS DESC
LIMIT 50;

-- 4. CoCo includes CLI, Desktop and Snowsight; keep interfaces distinct.
SELECT LOWER(INTERFACE) AS INTERFACE, USER_NAME,
       SUM(TOKEN_CREDITS) AS COCO_CREDITS, SUM(TOKENS) AS TOKENS,
       COUNT(DISTINCT REQUEST_ID) AS REQUESTS,
       SUM(TOKEN_CREDITS) / NULLIF(COUNT(DISTINCT REQUEST_ID), 0) AS CREDITS_PER_REQUEST
FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_COCO_USAGE_HISTORY
WHERE USAGE_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND USAGE_TIME < CURRENT_DATE()
GROUP BY 1, 2
ORDER BY COCO_CREDITS DESC;

-- 5. CoCo input/output/cache credit breakdown. Tokens do not all have the same rate.
SELECT LOWER(usage.INTERFACE) AS INTERFACE, model.KEY AS MODEL_NAME,
       SUM(model.VALUE:input::FLOAT) AS INPUT_CREDITS,
       SUM(model.VALUE:output::FLOAT) AS OUTPUT_CREDITS,
       SUM(model.VALUE:cache_read_input::FLOAT) AS CACHE_READ_CREDITS,
       SUM(model.VALUE:cache_write_input::FLOAT) AS CACHE_WRITE_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_COCO_USAGE_HISTORY usage,
     LATERAL FLATTEN(INPUT => usage.CREDITS_GRANULAR, OUTER => TRUE) model
WHERE usage.USAGE_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND usage.USAGE_TIME < CURRENT_DATE()
GROUP BY 1, 2
ORDER BY INTERFACE, MODEL_NAME;

-- 6. CoCo request drill-down. A request is not necessarily a completed user task.
SELECT INTERFACE, USER_NAME, REQUEST_ID, PARENT_REQUEST_ID, USAGE_TIME, TOKEN_CREDITS, TOKENS
FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_COCO_USAGE_HISTORY
WHERE USAGE_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND USAGE_TIME < CURRENT_DATE()
ORDER BY TOKEN_CREDITS DESC
LIMIT 25;

-- 7. Search serving and embedding; excludes refresh warehouse and storage costs.
SELECT DATABASE_NAME, SCHEMA_NAME, SERVICE_NAME, CONSUMPTION_TYPE,
       SUM(CREDITS) AS SEARCH_CREDITS, SUM(TOKENS) AS EMBEDDING_TOKENS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_DAILY_USAGE_HISTORY
WHERE USAGE_DATE >= DATEADD('day', -30, CURRENT_DATE()) AND USAGE_DATE < CURRENT_DATE()
GROUP BY 1, 2, 3, 4
ORDER BY DATABASE_NAME, SCHEMA_NAME, SERVICE_NAME, SEARCH_CREDITS DESC;

-- 8. Direct Cortex Agents surface. CoCo/CoWork usage must be measured separately.
SELECT AGENT_DATABASE_NAME, AGENT_SCHEMA_NAME, AGENT_NAME,
       COUNT(DISTINCT REQUEST_ID) AS REQUESTS, SUM(TOKEN_CREDITS) AS AGENT_CREDITS,
       SUM(TOKEN_CREDITS) / NULLIF(COUNT(DISTINCT REQUEST_ID), 0) AS CREDITS_PER_REQUEST
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND START_TIME < CURRENT_DATE()
GROUP BY 1, 2, 3
ORDER BY AGENT_CREDITS DESC;

-- 9. Direct Analyst calls only, not the Analyst portion already billed by an agent.
SELECT DATE_TRUNC('day', START_TIME) AS USAGE_DAY,
       SUM(REQUEST_COUNT) AS ANALYST_REQUESTS, SUM(CREDITS) AS ANALYST_CREDITS,
       SUM(CREDITS) / NULLIF(SUM(REQUEST_COUNT), 0) AS CREDITS_PER_REQUEST
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_ANALYST_USAGE_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND START_TIME < CURRENT_DATE()
GROUP BY 1
ORDER BY 1 DESC;

-- 10. Warehouse meter includes idle time. Keep separate from per-query attribution.
SELECT DATE_TRUNC('day', START_TIME) AS USAGE_DAY, WAREHOUSE_NAME,
       SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
       SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS_BEFORE_ADJUSTMENT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND START_TIME < CURRENT_DATE()
GROUP BY 1, 2
ORDER BY USAGE_DAY DESC, COMPUTE_CREDITS DESC;

-- 11. Repeated query shapes. Attribution excludes warehouse idle time.
SELECT QUERY_PARAMETERIZED_HASH, WAREHOUSE_NAME,
       COUNT(DISTINCT QUERY_ID) AS EXECUTIONS,
       SUM(CREDITS_ATTRIBUTED_COMPUTE) AS ATTRIBUTED_COMPUTE_CREDITS,
       SUM(CREDITS_ATTRIBUTED_COMPUTE) / NULLIF(COUNT(DISTINCT QUERY_ID), 0) AS CREDITS_PER_EXECUTION
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE()) AND START_TIME < CURRENT_DATE()
GROUP BY 1, 2
HAVING COUNT(DISTINCT QUERY_ID) > 20
ORDER BY ATTRIBUTED_COMPUTE_CREDITS DESC
LIMIT 50;