-- Read-only. Requires sql/30. Cost per validated item, not per usage-history row.
-- Reconcile failed/orphaned inference queries using query 3 in sql/40.
-- These are persisted scoring-query costs, not total pipeline or account costs.
-- Missing telemetry stays NULL. Wait for publication; never substitute zero.

WITH persisted AS (
    SELECT RUN_ID, SCORING_QUERY_ID,
           COUNT(*) AS ATTEMPTED_ITEMS,
           COUNT(CASE WHEN SCORE_STATUS = 'SUCCEEDED' THEN 1 END) AS VALIDATED_ITEMS,
           COUNT(CASE WHEN SCORE_STATUS = 'REVIEW_REQUIRED' THEN 1 END) AS REVIEW_ITEMS
    FROM STUDIO_DS.CURATED.TEXT_ENRICHMENT_RESULT
    WHERE SCORED_AT >= DATEADD('day', -30, CURRENT_DATE())
    GROUP BY RUN_ID, SCORING_QUERY_ID
), ai AS (
    SELECT QUERY_ID, SUM(CREDITS) AS AI_CREDITS, BOOLOR_AGG(IS_COMPLETED) AS IS_COMPLETED
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY
    WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE())
    GROUP BY QUERY_ID
), warehouse AS (
    SELECT QUERY_ID, SUM(CREDITS_ATTRIBUTED_COMPUTE) AS WH_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
    WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE())
    GROUP BY QUERY_ID
)
SELECT persisted.*, ai.AI_CREDITS, warehouse.WH_CREDITS,
       CASE WHEN ai.IS_COMPLETED AND warehouse.QUERY_ID IS NOT NULL
            THEN 1000 * (ai.AI_CREDITS + warehouse.WH_CREDITS) / NULLIF(VALIDATED_ITEMS, 0)
       END AS SCORING_CREDITS_PER_1000_VALIDATED_ITEMS,
       CASE WHEN ai.QUERY_ID IS NULL OR warehouse.QUERY_ID IS NULL OR NOT ai.IS_COMPLETED
            THEN 'INCOMPLETE_TELEMETRY'
            WHEN VALIDATED_ITEMS = 0 THEN 'NO_VALIDATED_OUTPUT'
            ELSE 'OBSERVED' END AS COST_STATUS
FROM persisted
LEFT JOIN ai ON ai.QUERY_ID = persisted.SCORING_QUERY_ID
LEFT JOIN warehouse ON warehouse.QUERY_ID = persisted.SCORING_QUERY_ID
ORDER BY RUN_ID;